In [3]:
ipv <- read.csv("campers_ipv_for_analysis_corrected_match.csv")
 
# descriptives
aggregate(ipv$Counts.IPV, list(ipv$Husb.Employment.Bin), FUN = mean) # pinakamataas female only
aggregate(ipv$Counts.IPV, list(ipv$Husb.Employment.Bin), FUN = sum) # pinakamataas male only and both employed
aggregate(ipv$Counts.IPV, list(ipv$Husb.Employment.Bin), FUN = var)
aggregate(ipv$Counts.IPV, list(ipv$Husb.Employment.Bin), FUN = lengh)
summary(ipv)
table(ipv$Counts.IPV) # many zeros

# reclassifying variables
ipv$Marital <- factor(ipv$Marital)
ipv$Husb.Educ.Level <- factor(ipv$Husb.Educ.Level)
ipv$Educ.Level <- factor(ipv$Educ.Level)
ipv$Region <- factor(ipv$Region)
ipv$LPG <- relevel(factor(ipv$LPG), ref = "Male only Employed")

  Group.1 x
1 0       0.3452381
2 1       0.3387253

  Group.1 x
1 0         29
2 1       1403

  Group.1 x
1 0       0.5179289
2 1       0.4563556

  Group.1 x
1 0         84
2 1       4142

      X.1             X          RespondentID        Year           Age
 Min.   :   1   Min.   : 9224   Min.   : 9719   Min.   :2017   Min.   :16.00
 1st Qu.:1057   1st Qu.:10486   1st Qu.:11034   1st Qu.:2017   1st Qu.:24.00
 Median :2114   Median :11742   Median :12353   Median :2017   Median :29.00
 Mean   :2114   Mean   :11744   Mean   :12343   Mean   :2017   Mean   :29.51
 3rd Qu.:3170   3rd Qu.:13023   3rd Qu.:13668   3rd Qu.:2017   3rd Qu.:34.00
 Max.   :4226   Max.   :14232   Max.   :14919   Max.   :2017   Max.   :49.00

     Region         Educ.Level      Educ.Years    Educ.Attained
 Min.   : 1.000   Min.   :0.000   Min.   : 0.00   Min.   :0.000
 1st Qu.: 5.000   1st Qu.:2.000   1st Qu.: 8.00   1st Qu.:3.000
 Median :10.000   Median :2.000   Median :11.00   Median :4.000
 Mean   : 9.354   Mean   :2.032   Mean   :10.24   Mean   :3.493
 3rd Qu.:13.750   3rd Qu.:3.000   3rd Qu.:12.00   3rd Qu.:5.000
 Max.   :17.000   Max.   :3.000   Max.   :17.00   Max.   :5.000
                                  NA's   :74
    Marital      Husb.Educ.Level Husb.Educ.Years  Husb.Employment
 Min.   :1.000   Min.   :0.000   Min.   : 0.000   Min.   :   0
 1st Qu.:1.000   1st Qu.:1.000   1st Qu.: 7.000   1st Qu.:5414
 Median :1.000   Median :2.000   Median :11.000   Median :7113
 Mean   :1.341   Mean   :1.891   Mean   : 9.516   Mean   :6731
 3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:11.000   3rd Qu.:9211
 Max.   :2.000   Max.   :3.000   Max.   :98.000   Max.   :9629
                                 NA's   :93
   Employment   Husb.Educ.Attained    Husb.Age     Emotional.IPV
 Min.   :   0   Min.   :0.000      Min.   :17.00   Min.   :0.0
 1st Qu.:   0   1st Qu.:1.000      1st Qu.:27.00   1st Qu.:0.0
 Median :   0   Median :3.000      Median :32.00   Median :0.0
 Mean   :2337   Mean   :2.812      Mean   :33.01   Mean   :0.2
 3rd Qu.:5211   3rd Qu.:3.000      3rd Qu.:38.00   3rd Qu.:0.0
 Max.   :9629   Max.   :5.000      Max.   :95.00   Max.   :1.0

 Less.Physic.IPV   More.Physic.IPV     Sexual.IPV      Husb.Employment.Bin
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000   Min.   :0.0000
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:1.0000
 Median :0.00000   Median :0.00000   Median :0.00000   Median :1.0000
 Mean   :0.09796   Mean   :0.03715   Mean   :0.03502   Mean   :0.9801
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:1.0000
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000   Max.   :1.0000

 Employment.Bin       LPG             Physical.IPV       ANY.IPV
 Min.   :0.0000   Length:4226        Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.0000   Class :character   1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.0000   Mode  :character   Median :0.0000   Median :0.0000
 Mean   :0.4165                      Mean   :0.1039   Mean   :0.2383
 3rd Qu.:1.0000                      3rd Qu.:0.0000   3rd Qu.:0.0000
 Max.   :1.0000                      Max.   :1.0000   Max.   :1.0000

   Counts.IPV          Male            Female
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:0.0000
 Median :0.0000   Median :1.0000   Median :0.0000
 Mean   :0.3389   Mean   :0.9801   Mean   :0.4165
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:1.0000
 Max.   :3.0000   Max.   :1.0000   Max.   :1.0000

   0    1    2    3
3219  650  289   68

In [4]:
# descriptives
aggregate(ipv$Counts.IPV, list(ipv$Employment.Bin), FUN = mean) # pinakamataas female only
aggregate(ipv$Counts.IPV, list(ipv$Employment.Bin), FUN = sum) # pinakamataas male only and both employed
aggregate(ipv$Counts.IPV, list(ipv$Employment.Bin), FUN = var)
aggregate(ipv$Counts.IPV, list(ipv$Employment.Bin), FUN = length)

  Group.1 x
1 0       0.3296837
2 1       0.3517045

  Group.1 x
1 0       813
2 1       619

  Group.1 x
1 0       0.4433944
2 1       0.4771432

  Group.1 x
1 0       2466
2 1       1760

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8672f010-76e5-4fe5-a087-2513d801c0e9' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>